steps:
- name: 'docker'
  args: ['pull', 'katalonstudio/katalon']
- name: 'ubuntu'
  args: ['echo', '"$$(pwd)"']
- name: 'docker'
  args: ['run', '--name', 'katalonstudio/katalon', '-t', '--rm', '-v', '"$$(pwd)":/tmp/project', 'katalonc.sh', '-projectPath=/tmp/project', '-browserType="Chrome"', '-retry=0', '-retryStrategy=immediately', '-testSuiteCollectionPath="Test Suites/Simple Test Suite Collection"', '--config', '-webui.autoUpdateDrivers=true', '-apiKey=$$KATALON_API_KEY']
  secretEnv: ['KATALON_API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/better-world-corp/secrets/KATALON_API_KEY/versions/1
    env: 'KATALON_API_KEY'